[package]
name = "secomp-2023-question-server"
version = "0.1.0"
edition = "2021"
publish = false
author = "Brenno Lemos <brenno@syndel.is>"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
tokio = { version = "1.14.0", features = ["macros", "rt-multi-thread"] }
axum = { version = "0.6.0", features = ["tower-log", "macros"] }
sqlx = { version = "0.7", features = ["runtime-tokio-native-tls", "postgres", "uuid", "time"] }
clap = { version = "4.0.0", features = ["derive", "env"] }
serde = { version = "1.0.130", features = ["derive"] }
tower = "0.4.11"
tower-http = { version = "0.3.0", features = ["trace"] }
jwt = "0.15.0"
hmac = "0.11.0"
sha2 = "0.9.8"
time = "0.3"
uuid = { version = "1.0", features = ["serde", "v4"] }
anyhow = "1.0.48"
async-trait = "0.1.51"
dotenv = "0.15.0"
env_logger = "0.9.0"
itertools = "0.10.1"
log = "0.4.14"
rand = "0.8.4"
thiserror = "1.0.30"
askama = "0.12.0"
