version: "3.7"

services:
  db:
    image: postgres:14
    ports:
      - 5432:5432
    networks:
      - public
      - private
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./dump:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=axum
      - POSTGRES_PASSWORD=axum
      - POSTGRES_DB=axum

volumes:
  pgdata:

networks:
  public:
  private:

